# Generated by Django 4.1.6 on 2023-02-08 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 11, 54, 9, 894024, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 2, 8, 11, 54, 14, 514708, tzinfo=datetime.timezone.utc), upload_to='media/post/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 11, 54, 17, 874053, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 2, 8, 11, 54, 28, 589371, tzinfo=datetime.timezone.utc), editable=False, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
